//
//  WeatherViewModel.swift
//  WeatherDashboard
//
import Foundation
import SwiftUI
import CoreLocation
import SwiftData
internal import Combine

// MARK: - Global Constants
// Default location is London (as per requirements)
// Used as fallback when errors occur or on initial app launch
let defaultLocationName = "London"
let defaultCoordinate = CLLocationCoordinate2D(latitude: 51.5072, longitude: 0.1276)

// MARK: - Weather ViewModel
// Main view model managing weather data and business logic
@MainActor
class WeatherViewModel: ObservableObject {

    // MARK: - Published Properties
    @Published var currentLocationName: String = defaultLocationName                /// Currently selected location name
    @Published var currentCoordinate: CLLocationCoordinate2D = defaultCoordinate    /// Current location's coordinates
    
    @Published var weatherApiResponse: WeatherAPIResponse?          /// Full API response
    @Published var currentWeather: CurrentWeather?                  /// Current weather conditions (temp, wind, humidity, etc.)
    @Published var dailyForecasts: [DailyForecast] = []             /// Array with 8-day forecast
    @Published var pointsOfInterest: [PointOfInterest] = []         /// Array with 5 point of interests

    @Published var adviceMessage: String = ""                       /// Advice message generated by OpenAI
    @Published var isLoadingAdvice: Bool = false                    /// Flag indicating if AI advice is being fetched
    
    var isLoading:Bool = false                                      /// Flag indicating weather data is loading
    var errorMessage:String? = nil
    var confirmationMessage:String? = nil
    
    private let weatherService = WeatherService()                   /// Service for fetching weather data from OpenWeatherMap API
    private let locationService = LocationService()                 /// Service for geocoding and POI searches using MapKit
    private let weatherAdviceOpenAI = WeatherAdviceOpenAI()         /// Service for AI-generated weather advice using OpenAI API

    private var modelContext: ModelContext?                         /// SwiftData Context (will be set by the environment)
    
    // MARK: - Initialisation
    // Initializes the view model and loads default location (London)
    // Called once when app launches (created as @StateObject in App struct)
    init() {
        // Load London data on initialization as required
        Task {
            await loadLocation(name: defaultLocationName, coordinate: defaultCoordinate, isInitialLoad: true)
        }
    }
    
    // MARK: - Main Location Loading Method
    // Loads weather data for a specified location
    // This is the primary orchestration method that:
    // 1. Checks if location exists in database
    //      1.1. If yes: loads from DB + fetches fresh weather
    //      1.2. If no: geocodes location, fetches weather & POIs, saves to DB
    // 2. Updates all @Published properties to trigger UI refresh
    //
    // - Parameters:
    //   - name: Location name to search for
    //   - coordinate: Fallback coordinates (used for initial London load)
    //   - isInitialLoad: If true, skip saving to database (for default location)
    func loadLocation(name: String, coordinate: CLLocationCoordinate2D, isInitialLoad: Bool = false) async {
        isLoading = true
        errorMessage = nil
        
        do {
            // STEP 1: Check if location already exists in database
            let location = try fetchLocation(name: name)
            
            if let savedLocation = location {
                // BRANCH A: Location found in database
                print("📍 Location '\(name)' found in database")
                
                // Update state with saved data
                currentLocationName = savedLocation.name
                currentCoordinate = savedLocation.coordinate
                pointsOfInterest = savedLocation.pointsOfInterest ?? []
                confirmationMessage = "Location '\(name)' loaded from storage."
                
                // Fetch fresh weather data (saved location might have stale weather)
                let weatherResponse = try await weatherService.fetchWeather(
                    latitude: savedLocation.latitude,
                    longitude: savedLocation.longitude
                )
                
                // Based on obtained values - request advice from OpenAI
                adviceMessage = ""
                requestAdviceFromOpenAI(location: name)
                
                // Update weather state (current + forecast)
                updateWeatherState(with: weatherResponse)
                
            } else {
                // BRANCH B: New location not in database
                print("🆕 Location '\(name)' not found - creating new entry")
                
                // New location: Geocode, fetch weather, fetch POIs, and save
                let finalCoordinate = isInitialLoad ? coordinate : try await locationService.geocode(locationName: name)
                
                // PARALLEL EXECUTION: Fetch weather and POIs simultaneously
                // This improves performance by running both API calls concurrently
                async let weatherTask = weatherService.fetchWeather(latitude: finalCoordinate.latitude, longitude: finalCoordinate.longitude)
                async let poiTask = locationService.searchPOIs(coordinate: finalCoordinate)
                
                let (weatherResponse, pois) = try await (weatherTask, poiTask)
                
                // Update all published state
                currentLocationName = name
                currentCoordinate = finalCoordinate
                pointsOfInterest = pois
                updateWeatherState(with: weatherResponse)
                
                // Based on obtained values - request advice from OpenAI
                adviceMessage = ""
                requestAdviceFromOpenAI(location: name)
                
                // STEP 2: Save location to database (unless it's initial London load)
                if !isInitialLoad {
                    try saveLocation(name: name, coordinate: finalCoordinate, pois: pois)
                    confirmationMessage = "Location '\(name)' saved and updated."
                }
            }
            
        } catch {
            handleError(error)
        }
    }
    
    // MARK: - AI Weather Advice
    // Requests weather advice from OpenAI based on current conditions
    // Runs asynchronously to avoid blocking the UI
    // Updates adviceMessage when response arrives
    //
    // - Parameter location: Location name for context in AI prompt
    private func requestAdviceFromOpenAI(location:String) {
        Task {
            isLoadingAdvice = true
            
            do {
                // Call OpenAI API with current weather parameters
                let advice = try await weatherAdviceOpenAI.getWeatherAdvice(
                    location: location,
                    temperature: currentWeather?.temp ?? 0.0,
                    humidity: currentWeather?.humidity ?? 0,
                    windSpeed: currentWeather?.windSpeed ?? 0.0
                )
                adviceMessage = advice
            } catch {
                print("Error: \(error.localizedDescription)")
                adviceMessage = "ERROR FROM OPEN AI"
            }
            
            isLoadingAdvice = false
        }
    }
    
    // MARK: - Database Operations
    
    // Fetches a saved location from database by name
    // Uses SwiftData's predicate system for type-safe queries
    //
    // - Parameter name: Location name to search for
    // - Returns: SavedLocation if found, nil otherwise
    // - Throws: Database errors
    private func fetchLocation(name: String) throws -> SavedLocation? {
        guard let context = modelContext else { return nil }
        
        // Create type-safe predicate using Swift macros
        // #Predicate is a compile-time checked query
        let predicate = #Predicate<SavedLocation> { $0.name == name }
        let descriptor = FetchDescriptor(predicate: predicate)
        
        // Execute query and return first result (should be only one due to unique constraint)
        return try context.fetch(descriptor).first
    }
    
    // Saves a new location to the database with its POIs
    // Establishes bidirectional relationships between location and POIs
    //
    // - Parameters:
    //   - name: Location name
    //   - coordinate: Geographic coordinates
    //   - pois: Array of points of interest
    // - Throws: Database save errors
    private func saveLocation(name: String, coordinate: CLLocationCoordinate2D, pois: [PointOfInterest]) throws {
        guard let context = modelContext else { return }
        
        // Create new SavedLocation instance
        let newLocation = SavedLocation(name: name, latitude: coordinate.latitude, longitude: coordinate.longitude)
        newLocation.pointsOfInterest = pois
        
        // Set the inverse relationship
        for poi in pois {
            poi.location = newLocation
        }
        
        // Insert into context and persist to database
        context.insert(newLocation)
        try context.save()
    }
    
    // Deletes a location and its associated POIs from database
    // POIs are automatically deleted due to cascade delete rule
    //
    // - Parameter location: Location to delete
    // - Throws: Database errors
    func deleteLocation(location: SavedLocation) throws {
        guard let context = modelContext else { return }
        
        // Delete triggers cascade: all associated POIs are also deleted
        context.delete(location)
        try context.save()
    }

    // Sets the SwiftData model context
    // Called from ContentView.onAppear() to inject the context
    //
    // - Parameter context: SwiftData model context from environment
    func setModelContext(_ context: ModelContext) {
        self.modelContext = context
    }
    
    // MARK: - Helper Methods
    
    // Handles errors by reverting to default London location
    // Ensures app always has valid weather data even after failures
    //
    // - Parameter error: The error that occurred
    private func handleError(_ error: Error) {
        // Gracefully manage errors by defaulting to London
        print("Error: \(error.localizedDescription)")
        errorMessage = "Could not load location. Reverting to \(defaultLocationName). Error: \(error.localizedDescription)"
        
        // Revert to London's data
        Task {
            await loadLocation(name: defaultLocationName, coordinate: defaultCoordinate, isInitialLoad: true)
        }
    }

    // Updates all weather-related @Published properties
    // Centralizes state updates to ensure consistency
    //
    // - Parameter response: API response containing all weather data
    private func updateWeatherState(with response: WeatherAPIResponse) {
        self.weatherApiResponse = response
        self.currentWeather = response.current
        // The API returns 8 days, which satisfies the requirement
        self.dailyForecasts = Array(response.daily.prefix(8))
    }

}

// MARK: - Extensions

// Makes CLLocationCoordinate2D conform to Equatable
// Needed for comparing coordinates in UI updates
// @retroactive allows conformance to be added outside the original module
extension CLLocationCoordinate2D: @retroactive Equatable {
    public static func == (lhs: CLLocationCoordinate2D, rhs: CLLocationCoordinate2D) -> Bool {
        lhs.latitude == rhs.latitude && lhs.longitude == rhs.longitude
    }
}

